# Generated by Django 3.0.11 on 2020-11-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtail_to_ion', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Collection',
        #     fields=[
        #         ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        #     bases=('wagtailcore.page',),
        # ),
        migrations.AddField(
            model_name='ionimage',
            name='rendition_type',
            field=models.CharField(default='jpegquality-70', max_length=128),
        ),
        # migrations.AlterField(
        #     model_name='contenttypedescription',
        #     name='content_type',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        # ),
        migrations.AlterField(
            model_name='ionmedia',
            name='thumbnail_checksum',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ionmedia',
            name='thumbnail_mime_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        # migrations.AlterField(
        #     model_name='ionmediarendition',
        #     name='name',
        #     field=models.CharField(choices=[], max_length=128),
        # ),
    ]
