# Generated by Django 3.0.11 on 2021-04-20 19:01

from django.db import migrations, models
import wagtail.images.models
import wagtail_to_ion.fields.files


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iondocument',
            name='file_last_modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ionimage',
            name='file_last_modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ionimage',
            name='rendition_type',
            field=models.CharField(default='jpegquality-70', max_length=128),
        ),
        migrations.AddField(
            model_name='ionmedia',
            name='file_last_modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ionmedia',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ionmedia',
            name='thumbnail_file_last_modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ionmedia',
            name='thumbnail_file_size',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ionmediarendition',
            name='file_last_modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ionmediarendition',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ionmediarendition',
            name='mime_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ionmediarendition',
            name='thumbnail_file_last_modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ionmediarendition',
            name='thumbnail_file_size',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ionmediarendition',
            name='thumbnail_mime_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ionrendition',
            name='checksum',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ionrendition',
            name='file_last_modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ionrendition',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ionrendition',
            name='mime_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='iondocument',
            name='file',
            field=wagtail_to_ion.fields.files.IonFileField(checksum_field='checksum', file_size_field='file_size', last_modified_field='file_last_modified', mime_type_field='mime_type', upload_to='documents', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='ionimage',
            name='file',
            field=wagtail_to_ion.fields.files.IonImageField(checksum_field='checksum', file_size_field='file_size', height_field='height', last_modified_field='file_last_modified', mime_type_field='mime_type', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width'),
        ),
        migrations.AlterField(
            model_name='ionmedia',
            name='file',
            field=wagtail_to_ion.fields.files.IonFileField(checksum_field='checksum', file_size_field='file_size', last_modified_field='file_last_modified', mime_type_field='mime_type', upload_to='media', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='ionmedia',
            name='thumbnail',
            field=wagtail_to_ion.fields.files.IonImageField(blank=True, checksum_field='thumbnail_checksum', file_size_field='thumbnail_file_size', last_modified_field='thumbnail_file_last_modified', mime_type_field='thumbnail_mime_type', null=True, upload_to='media_thumbnails', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='ionmedia',
            name='thumbnail_checksum',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ionmedia',
            name='thumbnail_mime_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='ionmediarendition',
            name='file',
            field=wagtail_to_ion.fields.files.IonFileField(blank=True, checksum_field='checksum', file_size_field='file_size', last_modified_field='file_last_modified', mime_type_field='mime_type', null=True, upload_to='media_renditions', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='ionmediarendition',
            name='thumbnail',
            field=wagtail_to_ion.fields.files.IonImageField(blank=True, checksum_field='thumbnail_checksum', file_size_field='thumbnail_file_size', last_modified_field='thumbnail_file_last_modified', mime_type_field='thumbnail_mime_type', null=True, upload_to='media_thumbnails', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='ionrendition',
            name='file',
            field=wagtail_to_ion.fields.files.IonImageField(checksum_field='checksum', file_size_field='file_size', height_field='height', last_modified_field='file_last_modified', mime_type_field='mime_type', upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'),
        ),
    ]
